### PR TITLE
Resolves webview button element name changes for media keys

### PR DESCRIPTION
**Pull request by megalithic**
- Google changed their element names from `sj-icon-button` to
`paper-icon-button`

- https://github.com/radiant-player/radiant-player-mac/issues/381

### CODE REVIEW

**Comment by megalithic** [comment]
@kbhomes, this is my first xcode/swift/objc project, so forgive me if the extra project related files shouldn't be included. i explicitly changed `radiant-player-mac/js/main.js`.

**Comment by kbhomes** [comment]
@megalithic No worries, I appreciate the your quick PR for this! I'll clean up the patch and merge as soon as I can. Version bumping only really happens when we're about to push another release so you don't have to worry about that.

**Comment by megalithic** [comment]
Outstanding @kbhomes. Love this app, and have been wanting an excuse to crack open xcode to see what it's like. :)

Not that it warrants a full on wiki, but, do y'all have a place to put neat tricks/tips/addons for Radiant Player? I have a handy bit of [apple/shell script to grab the current track info](https://gist.github.com/megalithic/cd957de7c6905e8bb2c3) for use in tmux or other CLI things that others may find useful.

**Comment by megalithic** [comment]
@kbhomes one final note; i just realized, that potentially `currentPlaybackMode` is not getting updated/set correctly. Not sure if that is another recent change or not.

**Comment by MarshallOfSound** [comment]
In order to future proof against further tag name changes why don't we simply remove the tag name from the selector. E.g  `#player [data-id="play-pause"]`.  
That selector seems specific enough but allows for these tag name changes

**Comment by chrismou** [comment]
:+1: Confirmed media keys now working again, thanks @megalithic

**Comment by megalithic** [comment]
my pleasure @chrismou; and @MarshallOfSound i'd be totally good with that. though, i'd let @kbhomes decide that as that level of specificity is used for a ton of things in the app and I wasn't willing to introduce more than the regressions I already have. :)

if there were tests, etc in place to catch regressions such as these, i'd totally feel more comfy doing it.

**Comment by kbhomes** [comment]
@megalithic I'm opting to close this because there are some locations in the code that still needed updating with the new selector, and a few other styling issues. I thought it would be easier to commit bb13b70ac672bf82c51aa712392010461198ce13 than to amend to this PR, but I'll certainly be crediting you in the release notes! I appreciate your quick diagnosis of the issue.

**Pull request closed without merging**
