### PR TITLE
Mobile ready

### PR DESCRIPTION
**Pull request by PythonProdigy**

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
LGTM - thanks!

**Comment by chrismou** [comment]
When you say mobile ready - am I going mad? How are you running it on mobile?

**Comment by jacobwgillespie** [comment]
The website not the app :)





On Tue, Dec 15, 2015 at 12:45 AM -0800, "Chris Chrisostomou" <notifications@github.com> wrote:












When you say mobile ready - am I going mad? How are you running it on mobile?

**Comment by chrismou** [comment]
Ha! Oh yeah. That'll teach me to not go on Github before I've had a coffee. :blush:

**Pull request merged**
