### PR TITLE
Added playbar rating fill for rdiant theme

### PR DESCRIPTION
**Pull request by chrismou**
Added fix for ratings thumbs in the now playing bar not having a fill on Rdiant theme

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
LGTM :shipit: 

@chrismou, after you've merged, can you release this as 1.6.1?  Will be good practice for releases.  The process is:

* checkout master and make sure it's up to date
* run `./scripts/prepare-release.sh minor` (major, minor, patch) and follow the prompts
* run `git push --tags` once it's completed

**Comment by jacobwgillespie** [comment]
Well, `./scripts/prepare-release.sh patch` :)

**Comment by chrismou** [comment]
Sounds good, I'll give it a go.

Don't want to start deluging users with updates, but good for a bit of practice ;-)

**Comment by chrismou** [comment]
OK, there we go. Let's see what happens :+1:

**Comment by jacobwgillespie** [comment]
It worked - congrats!

**Comment by jacobwgillespie** [comment]
It worked, congrats!

**Comment by chrismou** [comment]
@jacobwgillespie Hats off to you, that whole process was pretty slick. Really good work.

**Comment by chrismou** [comment]
Ah wait, looks like the github pages site hasn't updated  http://radiant-player.github.io/radiant-player-mac/

Was there another command to run to do that?

**Comment by jacobwgillespie** [comment]
No, it happens as part of the build...  It looks like probably the website got built before GitHub cleared their release cache.  I may need to look into how to circumvent that scenario.

For now, if you want it to build the website again, just `git commit --allow-empty -m 'Bump to build website'` and push that to master.

**Comment by jacobwgillespie** [comment]
So, somehow your tag didn't get pushed as master (I'm guessing it pushed only the tag and not master).  I fixed that!

**Pull request merged**
