### PR TITLE
Fix for window drag lag and UI freezes

### PR DESCRIPTION
**Pull request by chrismou**
This PR fixes the choppy, laggy effect you get when dragging the player around, and the UI freezes after minimising to dock.

Thanks to some great investigative work by @leemm, it's turned out that disabling the titlebar fixes all of these issues. So I've implemented the fix, made some tweaks to the colors and added a preference to toggle custom titlebar on/off.  I've set it to standard by default because the UI freezes are pretty crippling if you don't know how to work around them. And even then the player will act a bit strange until you restart. Switching it back to custom makes it exactly how it was before.

I'll add enough info in the changelog that anyone who actually reads the upgrade popup will know how to reactivate it.

I spent a while debating whether to make the titlebars match the colour of the header, or to use the "page" colour. I opted for the latter because with the colours matching the header the window controls look too high and the text/search box look too low

screenshot 2016-01-07 21 12 37

screenshot 2016-01-07 21 13 28

Thoughts? @radiant-player/radiant-player-mac

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
I have four thoughts:

1. Looks great!  I'm for this as a settings option
1. On this build I'm unable to drag the window with the custom title bar (and I am able on 1.6.2) so I'd like to figure out what changed to cause that
1. Generally I'd also be interested in figuring out what about the custom bar causes performance issues
1. Finally, if the custom bar is disabled, I think we should remove the CSS that's shifting the player controls (like menu, etc.) to the right (originally to make room for the window controls)

**Comment by chrismou** [comment]
Hey @jacobwgillespie 

* :+1: 
* afaik this dragging issue has been around since maybe 1.5, it's just never annoyed me enough to spend much time investigating. Thing is it's not intermittent for me, so it may help to have one of you guys to take a look as I don't have a "working" version to compare against. If your stock 1.6.2 is running fine, could you send me a copy? I'd be intrigued to see if I'm still see the issue. The UI freeze issue though - that's the one I'm concerned about. If you minimize the screen, then wait a bit and bring it back up, the UI is frozen (though some buttons do still seem to work). Resizing the screen even by a pixel instantly causes he UI to unfreeze. I could recreate this 100% of the time, prior to this fix.
* Ditto. It pains me a bit to make the custom titlebars non default, but it's just such a crippling issue if you're affected and don't know the fix, that I'm concerned about how many people would just try Radiant once, think it's broken and sack it off.
* I'll look into this. I did notice the positioning was off in the screenshots, but if I'm honest I completely forgot again till you mentioned it then.

So yeah, check it out when you get a sec. Interesting that your 1.6.2 works fine - like I say, mine's been fubar for a while. I've just got around it by never minimising the player :-/  Have you updated anything recently? OSX, Xcode, etc?

**Comment by jacobwgillespie** [comment]
Here's a copy of my (I think working) Radiant 1.6.2.

[Radiant Player.zip](https://files.zenhub.io/56941929868eed7b6ccc9475)

**Comment by jacobwgillespie** [comment]
@chrismou unless you're still working on this, we should probably merge (you've got my LGTM)

**Comment by chrismou** [comment]
Noticed an issue with button placement after maximize/minimize that I need to work out. Also decided to make this an option, but leave the default as the fancy header as it seems like a step back disabling it for everyone.

I'll wrap this up as soon as I get some time. Busy few days.

**Comment by chrismou** [comment]
Haven't forgotten about this - it's just fallen below a few other jobs in my priority list. Should hopefully find some time to get it sorted this weekend.

**Comment by chrismou** [comment]
@radiant-player/radiant-player-mac I think this PR should be sorted now. I'd like some opinions on the default titlebar state though, as I seem to be changing my mind every time I look at it.

- Default to standard OSX titlebar - fixes drag lag and UI freezes. Sadly, it means for a great many people they'll never see the custom titlebar
- Default to custom titlebar - looks much better, but means for a lot of people, they'll install Radiant for the first time and think it's broken.

In both cases you can switch to the other mode via preferences > appearance, but we all know most people don't go looking for solutions, they just give up.  So do we go for default stable or pretty?

Reading through what I've typed it seems pretty obvious, but as it's a major change to the default UI state I'd appreciate opinions...  :-)

**Comment by chrismou** [comment]
FYI changelog is out of date. I'll update it once we decide on the default state

**Comment by leemm** [comment]
The custom title bar really is screwed in El Capitan so I'd still default to the standard titlebar.  It's either that or some people will look at the app, decide it's too broken and then abandon never looking back.

That's not to say somebody couldn't look into the reasons the custom title bar isn't working, when there's spare time for a dev. :)

**Comment by chrismou** [comment]
@leemm Yeah, this is my line of thinking too. This I figure is a bit of an interim fix till we can puzzle out what the underlying cause is (plus it never hurts to have more customization options). Once I get some time I want to flick back through older releases and see if I can pinpoint when it started, which should be easier know we sort of know what's causing it.

Main thing I'm concerned about is if we switch to a standard titlebar, if we puzzle out the issue and fix in in a month, it'll be a bit confusing for people if we then randomly switch them back to a custom titlebar

**Comment by leemm** [comment]
Good point.  There's always the option of asking the user whether they want to use the custom title bar once its fixed and rolled out.  Anyone new will just get it by default.

When I was looking through the code I found out it was introduced during Yosemite but the comments state it's a customised version.  Now sure how easy it'll be to fix.

**Comment by chrismou** [comment]
@radiant-player/radiant-player-mac OK so 2/2 people who have tried the test build so far both managed to miss that they had to disable the custom titlebar, which makes my mind up for me.  I'll switch to off by default, and put a note on how to reactivate on the changelog.

Good news is the issue went away for both of them when they deactivated it \o/

Unless there's any serious objections, I'm going to merge this in this evening and log a ticket to investigate the cause of the lag when someone gets a chance.  I'd love to sink some time into it now but I've got too many other things on right now.

**Comment by leemm** [comment]
I thought that might happen...  just turn it off by default.  You've got to think about it from the user's point of view - if it doesn't work first time it's broken. ;)

**Pull request merged**
