### PR TITLE
Dark theme loading message colour

### PR DESCRIPTION
**Pull request by chrismou**
Missed this one yesterday. Just a tiny change to the loading message colour on dark themes to bring it in line with the header colours

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
Just on a side note, if you guys have CSS files in your repo with hard coded colors it might be worth your time moving to a CSS preprocessor like LESS or SCSS so that you can just put variables everywhere for these colors.

Then you won't "miss" a colour like this again :smile:

**Comment by chrismou** [comment]
I've thought about stripping it all out into sass before, but I just know I'll end up escalating it into tidying up all the themes and there's other things I'd rather be spending time on. Like the gmusic integration or the electron branch!

Maybe I'll sort it some time soon. Just another thing to add to the ever growing list ;-)

**Comment by chrismou** [comment]
Talking of gmusic.js, that's *definitely* next on the list...

**Comment by jacobwgillespie** [comment]
:+1:

**Pull request merged**
