### PR TITLE
Css: Redesign dark theme.

### PR DESCRIPTION
**Pull request by danielstuart14**
Make it much more beautiful. 
- Set header as cyan. (with transparency)
- Many UI fix
- Hide scrollbar. (with scroll)
- Menu icon color fix
- Feel Lucky color fix
- Etc...

Images: 
IMG 1

IMG 2

IMG 3

### CODE REVIEW

**Comment by ErikAbrahamson** [comment]
Looks good!

**Comment by chrismou** [comment]
Mate, that looks ace. Good work!

**Comment by FezVrasta** [comment]
I don't like the headers and I can't see why we should replace the orange with the cyan. I understand that you may like it more, but it's just a subjective choice.

Probably we should just keep the orange and add a cyan alternative, if you like to have it.

**Comment by matheusdias** [comment]
@danielstuart14 I liked your theme but i believe that the best option would be create this theme with another name (Black Cyan Theme). The Radiant developers can insert this new option on themes list.

**Comment by matheusdias** [comment]
@danielstuart14 I tested your theme but it have some problems, probably due changes in GPM html structure.

**Comment by jadengore** [comment]
I'm with @matheusdias on this one. If you could rebase and move this to a cyan theme it would be an awesome contribution.

**Comment by jadengore** [comment]
@danielstuart14 Any update on this PR?

**Comment by danielstuart14** [comment]
I'm without an OS X device, so, I can't do that until get a mac/hack...
Em 24/11/2015 05:37, "Edward Bramanti" <notifications@github.com> escreveu:

**Comment by chrismou** [comment]
Hey @danielstuart14 - would you have any issue with me fixing this pull request up?  Will most likely just move this into a separate "cyan" theme and restore the Spotify theme back to how it was.

**Comment by danielstuart14** [comment]
nope, for me it's okay.

2015-11-24 18:14 GMT-02:00 Chris Chrisostomou <notifications@github.com>:

> Hey @danielstuart14 <https://github.com/danielstuart14> - would you have
> any issue with me fixing this pull request up? Will most likely just move
> this into a separate "cyan" theme and restore the Spotify theme back to how
> it was.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radiant-player/radiant-player-mac/pull/348#issuecomment-159392268>
> .
>



-- 
daniel p. stuart

**Comment by chrismou** [comment]
OK cool, leave it with me. I've got it working but quite a few bits look broken - possibly due to element name changes by Google. I should be able to fix most of them from your screenshots though.

**Comment by chrismou** [comment]
Hey guys

I've created a new pull request here: https://github.com/radiant-player/radiant-player-mac/pull/424

If anyone has any time, I'd appreciate if you could look it over and let me know if I've missed anything!

**Pull request closed without merging**
