### PR TITLE
CONTRIBUTING.md draft file discussion

### PR DESCRIPTION
**Pull request by chrismou**
So here's a first draft of a proposed CONTRIBUTING.md file. For the most part it's a collection of points on contribution guidelines from other large Github projects, with a few extra bits thrown in.

I'll keep ammending this pull request till we've got it how we want it, then rebase it all before it's merged in.

Suggestions/opinions/feedback welcome :-)

p.s formatted version here: https://github.com/chrismou/radiant-player-mac/blob/contributing/CONTRIBUTING.md

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
Suggestion for PR review process:

For PR review / merges, I personally am an advocate of having the PR author merge their own PRs (if they have permission), but only after getting a sign-off (LGTM) from one of the project collaborators.  That other collaborator is responsible for code review and is equally responsible for the code change after the LGTM.  And if the PR author merges the PR, then nothing will get merged before it's ready, if the PR wasn't good to go.  Obviously it works a little differently with non-collaborator PRs...

**Comment by chrismou** [comment]
I'm in 2 minds about this. On a busier project, I'd ideally look for a couple of :+1:'s, but as people are busy and things are a bit quiet, for smaller PRs I'd personally be happy with just having one person review it. And yeah, fine with merging in myself, but would be interested to hear @kbhomes's opinion. I can understand if he's want to review all PRs before merging, but then we'd essentially be in the same position we were in before the collaborators were added.

@radiant-player/radiant-player-mac Any other thoughts?

**Comment by jadengore** [comment]
@jacobwgillespie I prefer dropping a :shipit: vs a LGTM :smile:

**Comment by jacobwgillespie** [comment]
Yep, :shipit: works :wink:

**Comment by jadengore** [comment]
@chrismou I really appreciate your section on squashing commits. This should keep the history of Radiant relatively clean, and hopefully people will follow the one fix/branch guideline. If there are no objections, I say :shipit:, we should get this in so others know how to properly contribute to Radiant.

**Comment by chrismou** [comment]
@jadengore Cheers dude. Still not sure how to address the bit about merging - the more I think about it, the more I'm finding myself agreeing with @jacobwgillespie about being responsible for your own merges.

Perhaps change that final line to:

> Even if you have write access to the repository, do not directly push or merge pull-requests without first allowing others time to review your changes. Ideally you should have at least one :+1:, :shipit: or LGTM before you merge into master. If your changes are substantial or high risk, you may want to wait for more than one. Use your own judgement.

@kbhomes What are your thoughts overall?

**Comment by jacobwgillespie** [comment]
I'm going to add my :+1: on that addition @chrismou.

And I'll add my :shipit: on this PR after that addition - we can always change the guidelines later if we need.

**Comment by chrismou** [comment]
Cool, guidelines updated, merging now. Cheers guys!

**Comment by jadengore** [comment]
@chrismou Might be nice to squash this next time, just a suggestion :wink:

**Comment by chrismou** [comment]
I thought I did? Oh god, how did that merge get in there? Ha!

No way I can let that go. Fixing now... :stuck_out_tongue_winking_eye:

**Comment by chrismou** [comment]
I thought I did? Oh god dammit, how did that merge get in there? Ha!

Where's the shame face emoji? :stuck_out_tongue_winking_eye:

**Comment by chrismou** [comment]
OK, I'm going to pretend that the guidelines weren't official until *after* the merge :wink:

**Comment by jacobwgillespie** [comment]
:+1:

**Pull request merged**
