### PR TITLE
Replace PayPal button with Gratipay

### LINKED ISSUE #461: Replace PayPal donations with Gratipay
Something to consider: https://gratipay.com/radiant-player/

### PR DESCRIPTION
**Pull request by jacobwgillespie**
Fixes #461

### CODE REVIEW

**Comment by chrismou** [comment]
So how's this work?

**Comment by jacobwgillespie** [comment]
Essentially people donate to the project's account.  Eventually those funds are paid out to the people working on the project (as far as I can tell, that part isn't fully implemented in Gratipay, but is coming shortly).

**Comment by jadengore** [comment]
Should we get this merged?

**Comment by jacobwgillespie** [comment]
I'd like to - just need a 👍 from somebody else in the project... 😉

**Comment by jadengore** [comment]
👍

**Comment by jacobwgillespie** [comment]
Nice :)

**Pull request merged**
