### PR TITLE
status bar rating buttons fill fix

### LINKED ISSUE #429: thumbs not reflected in control bar
image

I expected the thumb icons in the control bar (on rollover) to reflect my likes.

v 1.5 mac

### PR DESCRIPTION
**Pull request by chrismou**
Rating buttons in "now playing" status bar always showed as outlined even if thumbed up/down, due to an issue with a svg fill not working properly

Filled the background using css and the existing sprites

Fixes #429

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
Are those sprite URLs (like `sprites_extended_d5d41cbe37133fce94c32acca2b8435c21125ddb.png`) coming from Google?  Feels like something that'd be easy to break if so.  Maybe there's some way to dynamically detect the correct URL?

**Comment by chrismou** [comment]
It's actually been playing on my mind that this was a bit of a short sighted solution. Though any method that uses the Google sprite sheet in our own custom is probably a bad idea - I can't help feeling that it's just as likely they'll rearrange the sprite images as it is they'll rename the file (most likely, changing the sheet will trigger the rename at their end so either way, it's bound to break eventually).

I've ended up grabbing a copy of the sprite sheet to reference, so at least I know the image won't change.

I started playing with the idea of completely replacing those rating button graphics with our own, allowing for more control over colouring in custom themes (hence the commented out css) but I'm going to revisit this another time as part of a separate PR

**Comment by jacobwgillespie** [comment]
This LGTM until it's revisited in another PR, so :shipit:

**Comment by chrismou** [comment]
Made a quick tweak to change the referenced image from http > https. For sanity's sake, I'll merge once travis has done it's thing :+1:

**Pull request merged**
