### PR TITLE
custom css tweaks in response to Google's changes

### PR DESCRIPTION
**Pull request by chrismou**
Couple of custom CSS fixes in response to Google changes. Also removed a couple of unneeded rules.

Props to @MarshallOfSound for highlighting the slider button/loading spinner change

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
Heh, heh.  Technically it was google that "highlighted" the loader :smile: 

#Iamsofunny

**Comment by chrismou** [comment]
Ha!  Oh dear, where's a bad pun emoji when you need one?  :wink:

**Comment by jacobwgillespie** [comment]
LGTM :shipit:

**Comment by chrismou** [comment]
Will probably push a patch release out tonight.  Just waiting to hear back on a mini player issue someone's reported to see if I can get that sorted before I do.

**Pull request merged**
