### PR TITLE
Fix script warnings, remove style JS, simplify style loader

### PR DESCRIPTION
**Pull request by jacobwgillespie**
Inspired by the console screenshots in #523, this PR should clear all the JS errors from our code (a few of them are coming from Google).

Changes:

* Fix errors where elements that don't exist are attempted to be modified
* Remove the addition of JS files per style (we aren't using this feature)
* Generally simplify the logic in the style loader

### CODE REVIEW

**Comment by chrismou** [comment]
Seeing as you fixed up all the console errors, I just clipped on a quick fix for the lastfm-icon error. Saves putting in another PR :-P

Otherwise LGTM :shipit: :+1:

**Comment by jacobwgillespie** [comment]
What do you think about leaving WebkitDeveloperExtras enabled?  I feel like on 50% of the errors we get I have to enable it again, and on some of them we ask users to enable it.  Seems like it could be a good idea just to leave it in the context menu.

**Comment by chrismou** [comment]
It's a fair point. TBF I never thought there was much value in switching it off, but seeing as we've always historically done it it's become a bit of a habit.

I've rebased my commit and re-added it

**Comment by jacobwgillespie** [comment]
Sweet, merged

**Comment by BarakaAka1Only** [comment]
Just updated to 1.7.4 and almost everything looks horrible tried all the styles that radiant-player comes with and it's the same



no buttons

**Comment by jacobwgillespie** [comment]
What OS version are you using?

**Comment by BarakaAka1Only** [comment]
i am using Yosemite 10.10.5 it was working before i updated then that happened and i went back to the old version i was on (1.7.3) and its doing it there :S

**Pull request merged**
