### PR TITLE
Support headphone controls via @megalithic

### LINKED ISSUE #43: Apple EarPods button doesn't pause/resume music
When I use the headphones that came with my iPhone to listen to music with this app and press the button, iTunes opens instead of the music being paused.

The behavior should be:
Single press: pause
Double press: next song
Triple press: previous song

@kbhomes I'll look at this over this weekend and see if it's easy to implement. If so, I'll send you a pull request.

### LINKED ISSUE #203: Headset button press still opens iTunes.
I have a fairly standard headset, single button for pause and play, it only works with iTunes.

Don't know if this is a limitation of the OS or the App.

### PR DESCRIPTION
**Pull request by jacobwgillespie**
Uses DDHidLib to support headphone controls.  Props to @megalithic for
implementation - I (@jacobwgillespie) am committing this as @megalithic
as a cleanup of #384

Closes #43 
Closes #203

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
@radiant-player/radiant-player-mac this should be ready for review

**Comment by chrismou** [comment]
I don't think i have any wired headphones with controls so not sure I can test. I'll have a look around my cable drawer ;-)

I assume this won't support Bluetooth headphone controls?

**Comment by jacobwgillespie** [comment]
Yeah, IDK how this affects Bluetooth headsets (maybe it'll work?) - I don't have any to test.  I can confirm this works with EarPods though.

**Comment by chrismou** [comment]
I'll test it out. Would be an added bonus if it did, but it probably won't. OSX seems to assume all bluetooth controls want to interact with iTunes. Obviously :confused:

**Comment by chrismou** [comment]
OK so weird "issue" (sort of)

I don't have EarPods, but I have a pair of standard headphones with volume controls.  On master, when I hit volume up/down, the system volume changes. All good.

On the PR branch, hitting the volume down throws the following error to console:

Unknown key press seen -1

Though both volume buttons still seem to change the system volume. It just throws a random warning to console.

I'm not sure what the implications are of this (if any). I'm tempted to say it still works so no problem, but a random console warning suddenly appearing does concern me a bit.

**Comment by jacobwgillespie** [comment]
Yeah, I noticed this as well - not sure how important it is.

**Comment by chrismou** [comment]
@radiant-player/radiant-player-mac Any of you guys got a set of headphones with controls? If we can confirm that at least a couple of sets of headphones are working OK then we can probably assume it's a red herring.

The key will be testing a set with next/previous track controls. If that still works OK then I think we're probably good to go.

**Comment by jacobwgillespie** [comment]
@radiant-player/radiant-player-mac - anybody available to review this?  If not, I think this should be merged before the 1.6 release (hopefully tomorrow) and credited as at least enabling headphone controls on Apple EarBuds/Pods.

**Comment by chrismou** [comment]
I did work for me, and didnt seem to break anything except for that warning in console, so I'll give it a :+1: on that basis. As long as nothing's broken, we can work out where the warning's coming from later.

**Comment by jadengore** [comment]
@chrismou I'll test with BT headphones in a bit, I have a pair.

**Comment by chrismou** [comment]
It won't work with Bluetooth. Ideally looking for someone to test with a pair of wired headphones with controls to see if it still all works ok for them

**Comment by brianjking** [comment]
@chrismou If you have a build I'll happily test. I have a pair of RHA MA-750i's that are wired with controls & microphone.

**Comment by jacobwgillespie** [comment]
Here's a temp build: https://www.dropbox.com/s/muou5970nbu30gk/radiant-temp-build.zip?dl=0

**Comment by jacobwgillespie** [comment]
I'm going to go ahead and merge this for now - feel free to open an issue if you run into any bugs.

**Comment by jadengore** [comment]
Hey guys, sorry I never got a chance to try this out. Hope it all works

**Comment by brianjking** [comment]
@jacobwgillespie Sorry, I was traveling back to Chicago last night and didn't see your build in time. I've just tested and found the Volume + and - controls work great.

However, the play/pause buttons seem to open iTunes.

**Comment by brianjking** [comment]
Created issue as per your request @jacobwgillespie. See #466

**Pull request merged**
