### PR TITLE
Add preference to show notifications even when player is in focus

### PR DESCRIPTION
**Pull request by jscheel**
I was often confused by notifications not showing up when I was controlling the player. I found an old closed issue (#341) in which someone else was caught by this as well. I've added a preference to always show the notifications, even if the app is in focus.

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
LGTM :+1:

**Comment by chrismou** [comment]
I've just always just thought notifications on Radiant were flaky - I had no idea this was a feature.

Is there any reason why we can't just make this standard, rather than adding another preference?

**Comment by jscheel** [comment]
@chrismou I would prefer it. I just didn't want to modify the existing behavior without the approval of a project maintainer, so I threw it behind a preference for now. @jacobwgillespie any input here?

**Comment by jacobwgillespie** [comment]
Oh, yeah I'd vote for having the default be show notifications... I can PR
the switch later or you can of you'd like.

**Comment by jscheel** [comment]
@jacobwgillespie here you go: https://github.com/radiant-player/radiant-player-mac/pull/472

**Comment by jacobwgillespie** [comment]
:+1:

**Pull request merged**
