### PR TITLE
Feature/implements mikey

### PR DESCRIPTION
**Pull request by megalithic**
Implements headphone controls (e.g. like the ones found on apple iPhone earbuds). Uses [DDHidLib](https://github.com/Daij-Djan/DDHidLib).

@kbhomes:
In addition to the aforementioned enhancement, I started to change the rest of the `sj-` prefixed elements over to the recently-updated-via-Google `paper-` prefixed element names. This started breaking other things. I couldn't find any tests in the project, so was incredibly scared of regressions cropping up. I did update the CSS to reflect, but left some of the JS as the `sj-` prefixed element names.

This code feels awful, but I'm like a fish out of water with xcode in general, let alone ObjC/Swift. I totally understand if you want to never merge this in, I've just been wanting this feature added for a while, so figured I'd add it. (mostly i was just getting so annoyed with itunes opening automatically anytime i'd hit the play/pause button my IEM's controls).

I'll start learning more about xcode so I won't be manually adding frameworks/libs/etc and in general won't miss references in obvious places (e.g. forgetting to add to the headers).

Cheers!

### CODE REVIEW

**Comment by megalithic** [comment]
Cross referencing #381

**Comment by jadengore** [comment]
@megalithic Seems awesome! Can you rebase this? I'll review in a bit.

**Comment by megalithic** [comment]
@jadengore definitely. will get it rebased this week. thanks!

**Comment by megalithic** [comment]
@jadengore so sorry for the delay on this. i need to do more clean up on these changes and now that y'all have a contributing doc, i want to go through it and make sure i'm meeting y'alls coding standards.

**Comment by jadengore** [comment]
@megalithic Thanks! No worries :+1:

**Comment by jadengore** [comment]
@megalithic Ping! Would be great to see this merged.

@radiant-player/radiant-player-mac if you could do some review on this as well it would be appreciated.

**Comment by jacobwgillespie** [comment]
I'm closing this PR - I've rebased and cleaned and have re-submitted as #450.  @megalithic, you're still credited with the new commit.  :)

**Pull request closed without merging**
