### PR TITLE
Build app on Travis

### LINKED ISSUE #414: Release process
Mainly for @radiant-player/radiant-player-mac, but let's create some docs around the release process.  Who does releases, when can they happen, are we signing builds, etc.  This probably specifically involves @kbhomes.  I'd vote for a `docs` folder with a `RELEASE.md` that describes what has to happen.

### PR DESCRIPTION
**Pull request by jacobwgillespie**
This depends on #435 and is still in-progress.  Not yet ready for review.

Closes #414

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
@radiant-player/radiant-player-mac this is ready for review!

**Comment by jacobwgillespie** [comment]
Note that this reads the Sparkle appcast data directly from GitHub releases - if you edit a release description, you will find something like `<!-- SPARKLESIG xxxxxxxxxx -->` at the bottom of the description - that is providing the signature data to the website scripts.

**Comment by jacobwgillespie** [comment]
I've gone back and signed all the older releases so we'll have a full history in the appcast.

**Comment by jadengore** [comment]
@jacobwgillespie This looks great! Was curious about why you are using Go on Travis, but then I saw it was for a command-line utility. :+1:

**Comment by jacobwgillespie** [comment]
Yep, I believe that Travis uses github-release internally but I needed custom access.  I'm going to go ahead and merge and attempt a 1.6 deployment!  Fingers crossed!

**Pull request merged**
