### PR TITLE
Update dependencies and gitignore Pods directory

### PR DESCRIPTION
**Pull request by jacobwgillespie**
This PR updates dependencies and `gitignore`s the Pods directory.  This is a somewhat subjective change, so here's my main thoughts:

* Tracking the updates of third-party code in our repo contains a lot of junk commits and bogus noise on the diffs - we really only need to specify what our dependencies are, not track their changes
* Many of us wanting to contribute to Radiant will inadvertently cause a lot of merge conflicts after runs of `pod install` if we keep Pods under source control
* Downside: hacking on Radiant is not as simple as `git clone` - you now have to deal with cocoapods.  IMO this is an acceptable barrier to entry and isn't too complex (as the updated README indicates).

So, this is a subjective change, so feel free to weigh in with your opinions as well.

@radiant-player/radiant-player-mac

### CODE REVIEW

**Comment by chrismou** [comment]
The only downside I can see to this is that it makes the whole "the fix is in the master branch, compile your own version until the next version is out" a bit more difficult for people.  That said, if we're moving to more regular releases then it's not such an issue.

Personally, I'm just using the pods included in the repo so this is a bit of a change for me. But if it's as simple as just running `pod install` every so often then I don't see it being a major issue.

**Comment by jadengore** [comment]
@chrismou From what I know about CocoaPods, it's not always that simple.

This is an interesting issue. I'm all for less clutter in the repo, but I think we should make it as easy as possible for developers to fork and PR their changes. If we can find a good, reliable balance I'm down with moving forward with this change.

**Comment by sleepynate** [comment]
@jadengore @chrismou It's not *always* that simple, but oftentimes it's simpler – a `pod install` is really only ever needed when the dependencies change, so only if you see changes to `Podfile` or `Podfile.lock` coming down from master. Most people will not have to run `pod install` often, probably only they're just pulling down the source for builds once in a while. After doing just that, I came immediately here to see if anyone had proposed ignoring them.

If you want to lock your dependencies in (perhaps to force compatibility with an old version of a library), pulling them down from CocoaPods and committing them is the way to go. Generally those problems can be solved with `Podfile.lock` and the `Pods/` directory can be safely ignored.

**Comment by jacobwgillespie** [comment]
I'll close this for now - we can revisit later if we'd like, but for now, it works as-is.

**Comment by jacobwgillespie** [comment]
@radiant-player/radiant-player-mac - do we have any updated opinions on this?  Should we version-lock our dependencies in the Podfile and remove them from the repo?

**Pull request closed without merging**
