### PR TITLE
Use gmusic.js internally

### PR DESCRIPTION
**Pull request by jacobwgillespie**
This supersedes work done at #402.  It was easier to re-implement than to deal with the many merge conflicts.  :smile: 

**Still a work in progress**

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
This appears to be working except for an issue encountered with gmusic.js: https://github.com/gmusic-utils/gmusic.js/issues/33

**Comment by chrismou** [comment]
Ha! Yeah, probably a good shout.

Will need to re-add the last.fm scrobbling stuff. It's gone against since you ported it to a new branch

**Comment by chrismou** [comment]
I can't remember what else there was that was broken. I seem to remember some weirdness with the mini player?  It's a bit of a haze.  I'll check out the branch tomorrow and check it

**Comment by jacobwgillespie** [comment]
Okay, @radiant-player/radiant-player-mac, this is ready for review.  https://github.com/gmusic-utils/gmusic.js/pull/35 was merged and that resolved all remaining issues I've encountered or that existed in #402.  Everything looks like it's working to me.

I decided that it's probably not a good idea to check the entire node_modules dir into source control, so I gitignore'd it and created `scripts/update-javascript-dependencies.sh`.  There's a note in the README about it.

**Comment by jacobwgillespie** [comment]
Oh and @chrismou I added the LastFM fix back as well.  :+1:

**Comment by chrismou** [comment]
Ah yeah, the seconds/milliseconds last.fm fix. I knew I'd changed something but couldn't remember what it was ;-)

I've built the branch and I'll keep using it for the rest of the day to see if I notice anything. Will post back here later :+1: 

Only thing I've noticed so far is it's spitting a lot of debug out to console. Probably worth switching some of that before we merge.

**Comment by jacobwgillespie** [comment]
Good catch - disabled debug messages :)

**Comment by chrismou** [comment]
Looks like the miniplayer is still being funny. All songs are showing as thumbed up for me (but only in the miniplayer).  Clicking the icon does what it's expected to do (loves, unloves) but the icon state never changes

screenshot 2016-03-30 14 17 50

**Comment by jacobwgillespie** [comment]
Any more details on how to reproduce?  It's working for me, but this is what I'm doing:

* Start a playlist that has a liked track down the list
* The mini player is showing no rating
* Skip forward to that track
* Miniplayer is showing thumbs up
* Skip to next song
* Miniplayer shows no rating

I've tried forward and backwards, stopping and starting, controls in the miniplayer / keyboard / app and it seems to work.  You may be doing something different though.

**Comment by chrismou** [comment]
OK, I've not been able to reproduce this since. I'll assume it was cache until I can prove otherwise

**Comment by jadengore** [comment]
@jacobwgillespie I would encourage you to also clean up the diff. A lot of the whitespace you removed have made this diff harder to read. Might be useful to do some linting like this in a separate commit.

**Comment by chrismou** [comment]
All the whitespace changes are in one file, so it's not as bad as it looks.

All looks good to me. Not had any issues in the last 5 hours. last.fm stuff all seems to still be working. Mini player working as expected and interacting with the web view OK

:muscle::shipit::point_right:

**Comment by jadengore** [comment]
@chrismou :+1: to shipping this :shipit:

**Comment by jacobwgillespie** [comment]
Sweet - I may do a separate PR sometime for whitespace cleanup.  :)

**Pull request merged**
