### PR TITLE
macOS Sierra and above Blocked Plugin Fix + Legacy Xcode Building

### PR DESCRIPTION
**Pull request by BarakaAka1Only**
Thanks to @xrubioj for pointing the his solution

This fix addresses the Blocked Plugin issue and UI properties are
usable than a blanked out UI from @xrubioj original PR
radiant-player#670

Legacy Build System is needed so i enabled it in my workspace

Only if you set `UseModernBuildSystem=NO` in the Workspace setting

```
Xcode 9.3 adds a new IDEWorkspaceChecks.plist file to a workspace’s
shared data, to store the state of necessary workspace checks.
Committing this file to source control will prevent unnecessary
rerunning of those checks for each user opening the workspace.
```

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
I've updated the build on Travis CI so it does produce builds again, but it seems to still be crashing - @BarakaAka1Only you want to take a look when you have a moment?

**Comment by BarakaAka1Only** [comment]
@jacobwgillespie I went ahead and merged all the changes and everything passed ;)

**Comment by xrubioj** [comment]
@BarakaAka1Only @jacobwgillespie See issue #674 about the crash. :)

**Comment by BarakaAka1Only** [comment]
@jacobwgillespie @xrubioj sorry been very busy at work i went ahead and merged the branch with @xrubioj excellent fix for the crash issue so that the rest with the non-media keys and such (blocked plug-in) is fixed! (yes i've tested it before merging)

**Pull request merged**
