### PR TITLE
Integrate with Travis CI

### PR DESCRIPTION
**Pull request by jacobwgillespie**
This PR is not yet ready to merge.  ~~However, @kbhomes, can you please authorize Travis CI to access this organization?  The security settings are such that we cannot currently add projects to Travis.~~

To follow along with development/testing, I'm pushing these commits to @jacobwgillespie/radiant-player-mac - builds are here: https://travis-ci.org/jacobwgillespie/radiant-player-mac/builds

This depends on #417 being merged first.

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
Just rebased against the `changelog` branch, so this now depends on #417.  I'm going to start specing out some deploy scripts and they're going to need the changelog info.

**Comment by jacobwgillespie** [comment]
Since #417 has been merged, this has been rebased onto `master`

**Comment by jacobwgillespie** [comment]
Okay, @radiant-player/radiant-player-mac, this is ready for review.  I've removed everything related to releases, so this PR only adds basic building and testing on Travis, but not automated releases.  That will come in a later PR, and we can merge this early so that other PRs will begin to test correctly on Travis.

**Comment by chrismou** [comment]
Looking good - only thing I spotted was the readme badge points at your travis - might be worth updating it to the organisation url `[Build Status](https://travis-ci.org/radiant-player/radiant-player-mac)`

**Comment by jacobwgillespie** [comment]
Good catch - fixed and I'll merge!

**Pull request merged**
