### PR TITLE
Flex Update

### PR DESCRIPTION
**Pull request by BarakaAka1Only**
Due to Google updating the UI on Google Play Music, they added new
changes. This fixes all the Flex related issues for Yosemite and lower
OS’s. This is a fresh re-done CSS file!

## **Screenshots**

**Before:**

image

image

image

image

**After:**

image

image

image

image

-Baraka

### CODE REVIEW

**Comment by chrismou** [comment]
Screenshots look good, but I'm without a Mac for the next few weeks at least, so will have to leave it to @jacobwgillespie to test :disappointed: :

**Comment by jacobwgillespie** [comment]
Yep, LGTM, merging.  🎉

**Comment by jacobwgillespie** [comment]
Well, merging after the automated tests complete.  :)

**Comment by BarakaAka1Only** [comment]
Awesome!

**Comment by MarshallOfSound** [comment]
@jacobwgillespie @chrismou FYI your themes probably got hit with this new UI

https://github.com/gmusic-utils/gmusic-theme.js/commit/71b83196ca7fd24e677c6a2d16ce9fa43e3a78fb

**Comment by chrismou** [comment]
I clearly did not pick a good time to be mac-less

Even with our robust theming system... 😉

**Pull request merged**
