### PR TITLE
Build website with Jekyll

### PR DESCRIPTION
**Pull request by jacobwgillespie**
This depends on #433 getting merged first.

* Removes unused image, JS, and CSS assets
* Replaces Slick (the image carousel) with an updated version on a CDN (mainly for https support)
* Optimizes image assets to reduce bandwidth
* Adds Jekyll with templated release notes, homepage, and appcast (for app updates)
* Integrates with automated Travis builds

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
@radiant-player/radiant-player-mac this is ready for review

**Comment by jacobwgillespie** [comment]
If you'd like to test this, try running `./scripts/build-website.sh` then `cd website/_site` and check out the results.

**Comment by chrismou** [comment]
Just a thought - as this is triggered by Travis, does this mean it'll automatically deploy after *any* commit to master?

**Comment by jacobwgillespie** [comment]
Yes, that is correct and is by design.  For the website, any commit to master will sync gh-pages with the website.  It is limited to the master branch, so other branches won't go to gh-pages.  I think this is the behavior we want for the website.

For automatically building the app itself, that will have some different logic (based on tags, so that when we tag `1.2.3` it will build and deploy `1.2.3`, but only on that specific commit).

**Comment by chrismou** [comment]
Seems to be a merge conflict in index.html.  Let me know when that's sorted and I'll check it out.

And don't forget to port over the PR from last night as I think it's included in the "old" section ;-)

**Comment by jacobwgillespie** [comment]
Okay, merge conflicts are resolved and this should be good to go

**Comment by chrismou** [comment]
Yo - haven't forgotten. Just getting a `./scripts/build-website.sh: line 5: bundle: command not found` error, which I'm guessing is something to do with not having the right gems installed, maybe.

Trying to work it out now. If it is specific ruby gems that need installing, will these need specifying in the travis config?

**Comment by jacobwgillespie** [comment]
Bundler is assumed to exist already (it's commonly installed with ruby) and is preinstalled on Travis.  On your local machine, you can `gem install bundler` to grab a copy.

**Comment by jacobwgillespie** [comment]
Oh, and once you have bundler installed, you run `bundle install` to install the other dependencies.  Anyways, again this is something Travis does automatically.

**Comment by chrismou** [comment]
Spent the past 2 minutes trying to work out what that notification sound was - turns out it was GitHub telling me you'd replied. This is what happens when I don't have music playing :anguished: 

OK, will try that and report back shortly!

**Comment by chrismou** [comment]
Oh and I went through the changelog - nice one logging the ticket. I'll push that up too when I'm done with this.

**Comment by jacobwgillespie** [comment]
I just rebased this - you may need to re-pull

**Comment by chrismou** [comment]
Will do :+1:

**Comment by andrewnorell** [comment]
I have a `favicon.ico` file to contribute once this PR is merged. :)

**Comment by chrismou** [comment]
Only issue with the build process was `@options[:href_ignore]` will be renamed in a future 3.x.x release: http://git.io/vGHHy` -- not sure if that's a Jekyll thing though

Aside from that, seems to be looking good. Though I'm making a mental note to rewrite that carousel to be pure CSS - the performance of that slick slider is awful.

:shipit:

**Comment by jacobwgillespie** [comment]
That's the html test tool - we can fix later I think...

Merging!

@andrewnorell, ready for the favicon!

**Pull request merged**
